"""annulation tracee sortiefin versementscol

Ajoute Annule/AnnulePar/DateAnnulation/MotifAnnulation sur SortieFin et
VersementScol (audit P1-02/P1-03/B7) : ComptabiliteService.annuler_mouvement
et VersementService.annuler_versement marquent desormais ces enregistrements
au lieu de les supprimer physiquement, en conservant une piste d'audit.

server_default='false' sur Annule (NOT NULL) : necessaire pour que l'ajout
de colonne reussisse sur une table contenant deja des lignes (les
enregistrements existants sont consideres non-annules par defaut).

IF NOT EXISTS (SQL brut plutot que op.add_column) : les modeles SortieFin
et VersementScol declarent deja ces colonnes, donc une base neuve creee via
create_tables() (Base.metadata.create_all) les a deja au moment ou cette
revision est rejouee (bug decouvert par la CI, chantier C2).

Revision ID: 6f2b3468174e
Revises: 71dbc5eb1292
Create Date: 2026-07-16 22:22:05.248492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2b3468174e'
down_revision: Union[str, Sequence[str], None] = '71dbc5eb1292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    for table in ('SortieFin', 'VersementScol'):
        op.execute(sa.text(
            f'ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "Annule" BOOLEAN NOT NULL DEFAULT false'
        ))
        op.execute(sa.text(f'ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "AnnulePar" VARCHAR(50)'))
        op.execute(sa.text(f'ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "DateAnnulation" TIMESTAMP'))
        op.execute(sa.text(f'ALTER TABLE "{table}" ADD COLUMN IF NOT EXISTS "MotifAnnulation" TEXT'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('VersementScol', 'MotifAnnulation')
    op.drop_column('VersementScol', 'DateAnnulation')
    op.drop_column('VersementScol', 'AnnulePar')
    op.drop_column('VersementScol', 'Annule')
    op.drop_column('SortieFin', 'MotifAnnulation')
    op.drop_column('SortieFin', 'DateAnnulation')
    op.drop_column('SortieFin', 'AnnulePar')
    op.drop_column('SortieFin', 'Annule')
    # ### end Alembic commands ###
