"""creer table audit log

IF NOT EXISTS (SQL brut plutot que op.create_table) : le modele AuditLog est
importe dans create_tables(), donc une base neuve creee via
Base.metadata.create_all() a deja cette table au moment ou cette revision
est rejouee (bug decouvert par la CI, chantier C2).

Revision ID: a369634edd2b
Revises: 6f2b3468174e
Create Date: 2026-07-16 22:26:09.944731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a369634edd2b'
down_revision: Union[str, Sequence[str], None] = '6f2b3468174e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.text('''
        CREATE TABLE IF NOT EXISTS "AuditLog" (
            "IDAuditLog" SERIAL PRIMARY KEY,
            "IDUtilisateur" INTEGER REFERENCES "Utilisateur" ("IDUtilisateur") ON DELETE SET NULL,
            "Action" VARCHAR(50) NOT NULL,
            "TableCible" VARCHAR(50) NOT NULL,
            "IDCible" INTEGER NOT NULL,
            "AncienneValeur" TEXT,
            "NouvelleValeur" TEXT,
            "Motif" TEXT,
            "DateAction" TIMESTAMP NOT NULL
        )
    '''))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AuditLog')
    # ### end Alembic commands ###
