"""creer table audit log

Revision ID: a369634edd2b
Revises: 6f2b3468174e
Create Date: 2026-07-16 22:26:09.944731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a369634edd2b'
down_revision: Union[str, Sequence[str], None] = '6f2b3468174e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditLog',
    sa.Column('IDAuditLog', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IDUtilisateur', sa.Integer(), nullable=True),
    sa.Column('Action', sa.String(length=50), nullable=False),
    sa.Column('TableCible', sa.String(length=50), nullable=False),
    sa.Column('IDCible', sa.Integer(), nullable=False),
    sa.Column('AncienneValeur', sa.Text(), nullable=True),
    sa.Column('NouvelleValeur', sa.Text(), nullable=True),
    sa.Column('Motif', sa.Text(), nullable=True),
    sa.Column('DateAction', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['IDUtilisateur'], ['Utilisateur.IDUtilisateur'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('IDAuditLog')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AuditLog')
    # ### end Alembic commands ###
